# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Autores"
url = "/autores"
weight = 2

[[main]]
name = "Sobre nosotros"
url = "/nosotros"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contacto"
url = "/contacto"
weight = 5


# footer menu - not needed for now
# [[footer]]
# name = "Sobre nosotros"
# url = "/nosotros"
# weight = 1
